### ISSUE TITLE
Crash on Android 5.0+

### ISSUE THREAD

**Issue by guzno** [Tealium/android-library#2]
We are seeing a crash in the Tealium library (4.1c) on Samsung, HTC, Sony and some other devices running Android 5.0+. The crash seems to be related to some lifecycle event that Tealium reacts to.

We get the following stacktrace:

android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:161)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.WebView.getFactory(WebView.java:2193)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2188)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2247)
       at android.view.View.(View.java:3795)
       at android.view.View.(View.java:3909)
       at android.view.ViewGroup.(ViewGroup.java:507)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
       at android.webkit.WebView.(WebView.java:547)
       at android.webkit.WebView.(WebView.java:492)
       at android.webkit.WebView.(WebView.java:475)
       at android.webkit.WebView.(WebView.java:462)
       at android.webkit.WebView.(WebView.java:452)
       at com.tealium.library.H$1.run()
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5944)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:137)
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:133)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.WebView.getFactory(WebView.java:2193)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2188)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2247)
       at android.view.View.(View.java:3795)
       at android.view.View.(View.java:3909)
       at android.view.ViewGroup.(ViewGroup.java:507)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
       at android.webkit.WebView.(WebView.java:547)
       at android.webkit.WebView.(WebView.java:492)
       at android.webkit.WebView.(WebView.java:475)
       at android.webkit.WebView.(WebView.java:462)
       at android.webkit.WebView.(WebView.java:452)
       at com.tealium.library.H$1.run()
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5944)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by ChadHartman** [comment]
Researching but [this](http://stackoverflow.com/questions/29575313/namenotfoundexception-webview) appears to be what's going on:
> It's likely that this is happening in the very short time frame immediately after Lollipop's Android System WebView application updates.

**Comment by ChadHartman** [comment]
Thank you for the issue submission. Upon further research the linked StackOverflow explanation does indeed seem to describe what's causing the crash. I'm closing this issue, and the next iteration of the library will trap for this case.

**Comment by jaredsburrows** [comment]
What was your resolution?

**Comment by ChadHartman** [comment]
In version 4.1.1, WebView instantiation was wrapped in a try-catch to catch the NameNotFoundException and prevent a crash. I was unable to determine whether the app needed a re-start or whether the WebView could load later. The library queues track calls until the WebView is created and there is network connection, so no data is lost. 

If you don't mind me asking; are you implementing our library or did this issue come up on a search?

**Comment by jaredsburrows** [comment]
Your issue came up in my search. This issue seems related to: http://stackoverflow.com/questions/29575313/namenotfoundexception-webview

**Comment by feludens** [comment]
This just happened to me. We are using Tealium's 5.0.0 version, so whatever you guys did on 4.1.1 was either not transferred into the new version, or it didn't work. I will try to create a new issue on the new version page.
