### ISSUE TITLE
"pointerIndex out of range"

### ISSUE THREAD

**Issue by Arne517** [Tealium/android-library#3]
Hi guys,

Recently we updated the tealium library in one of our clients application to 4.1.1 (full).
In our crash tracker we started to see this issue:

```
java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getY(MotionEvent.java:1998)
       at android.support.v4.view.MotionEventCompatEclair.getY(MotionEventCompatEclair.java:35)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getY(MotionEventCompat.java:95)
       at android.support.v4.view.MotionEventCompat.getY(MotionEventCompat.java:228)
       at android.support.v4.widget.SwipeRefreshLayout.onTouchEvent(SwipeRefreshLayout.java:803)
       at android.view.View.dispatchTouchEvent(View.java:8464)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
       at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2264)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
       at com.tealium.library.I.onTouchEvent()
       at android.view.View.dispatchTouchEvent(View.java:8464)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2425)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2318)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1696)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2279)
       at android.view.View.dispatchPointerEvent(View.java:8654)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4035)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3901)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3463)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3516)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3482)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3592)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3490)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3649)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3463)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3516)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3482)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3490)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3463)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5718)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5692)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5663)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5808)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:195)
       at android.app.ActivityThread.main(ActivityThread.java:5321)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

We do use a `SwipeRefreshLayout` on one of our screens, but sadly enough we're not able to reproduce this. It doesn't seem to be specific for a manufacturer or an OS version.
Do you guys have any clue what's going on here?

**Comment by ChadHartman** [comment]
My apologies for the delay in responding to you.

We have seen this issue once before. Similarly, the issue was unreproducible and took place in a support library view. The ```com.tealium.library.I.onTouchEvent()``` method performs a ```MotionEvent``` proxy where it subscibres to the touch event and sends it off to its actual target. This is why the Tealium Library shows up in the stack trace. The ```I``` object performs no modification to the ```MotionEvent```, and similar to the Android ```ViewGroup``` source; sends the event down the view hierarchy. There's no apparent reason for the ```IllegalArgumentException```, so no fix has been applied. 

**Options**

1. Exclude using the relevant activity by using the [exclude activies](https://github.com/Tealium/android-library/wiki/API-Tealium.Config#tealiumconfig-setexcludedactivityclassessetclass-extends-activity-excludedactivityclasses) config option, and manually track UI events using the [track call](https://github.com/Tealium/android-library/wiki/API-Tealium#void-trackobject-activityvieworthrowable-mapstring--optionaldata-string-eventname). 

2. Switch to manual tracking only with the 4.1.1c library. 

Any feedback is most welcome, and we'll be sure to get back to you promptly.
